name: "test"
backend: "example"

input [
    {
      name: "prompt"
      data_type: TYPE_STRING
      dims: [ -1 ]
    }
]

output [
    {
      name: "output"
      data_type: TYPE_STRING
      dims: [ -1 ]
    }
]
